name: playlist_saver
description: Flutter project.
publish_to: 'none'
version: 2.2.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:
  shared_preferences: ^2.5.3
  share_plus: ^10.0.0
  url_launcher: ^6.3.1
  easy_dynamic_theme: ^2.3.1
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  fluttertoast: ^8.2.12
  web_scraper: ^0.1.4
  animations: ^2.0.11
  share_handler: ^0.0.22
  flutter_image_compress: ^2.3.0
  cupertino_icons: ^1.0.2
  permission_handler: ^11.3.0
  async_redux: ^25.4.0
  dynamic_system_colors: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true

  assets:
    - assets/


