name: playlist_saver
description: Flutter project.
publish_to: 'none'
version: 1.5.3

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  shared_preferences:
  share:
  url_launcher:
  easy_dynamic_theme:
  spotify_metadata:
  sqflite:
  path_provider:
  fluttertoast:
  web_scraper: ^0.1.4
  animations: ^2.0.3
  share_handler:
  flutter_image_compress: ^1.1.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/


