name: playlist_saver
description: Flutter project.
publish_to: 'none'
version: 2.1.1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:
  shared_preferences:
  share_plus: ^10.0.0
  url_launcher:
  easy_dynamic_theme:
  sqflite:
  path_provider:
  fluttertoast:
  web_scraper: ^0.1.4
  animations:
  share_handler:
  flutter_image_compress: ^2.3.0
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.7.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true

  assets:
    - assets/


